/**
 * Shared activity stats snapshot (build-time).
 *
 * Generated by `scripts/fetch-activity-stats.mjs`.
 *
 * Providers:
 * - github: all-time counters + last-12-month contribution calendar
 * - linear / jira: created, closed, open, bugsReported (combined in UI)
 */

import activityStatsJson from "@/data/activity-stats.json";

export type ContributionDay = {
  date: string;
  count: number;
  level: 0 | 1 | 2 | 3 | 4;
  weekday: number;
};

export type ContributionWeek = {
  contributionDays: ContributionDay[];
};

export type GithubActivityStats = {
  login: string;
  /** Account created / start of all-time window */
  from: string;
  /** End of all-time window (fetch time) */
  to: string;
  /** Start of contribution calendar (last 12 months) */
  calendarFrom: string;
  /** End of contribution calendar */
  calendarTo: string;
  totalContributions: number;
  commits: number;
  issues: number;
  pullRequests: number;
  codeReviews: number;
  calendar: {
    weeks: ContributionWeek[];
  };
};

/** Linear or Jira issue-tracker snapshot for the authenticated user */
export type TrackerActivityStats = {
  created: number;
  closed: number;
  open: number;
  bugsReported: number;
  updatedAt?: string;
};

export type ActivityStats = {
  updatedAt: string;
  github: GithubActivityStats;
  linear: TrackerActivityStats | null;
  jira: TrackerActivityStats | null;
};

export const activityStats = activityStatsJson as ActivityStats;

/** Sum Linear + Jira counters for the combined trackers row. */
export function combinedTrackerStats(
  linear: TrackerActivityStats | null,
  jira: TrackerActivityStats | null
): TrackerActivityStats | null {
  if (!linear && !jira) return null;
  return {
    created: (linear?.created ?? 0) + (jira?.created ?? 0),
    closed: (linear?.closed ?? 0) + (jira?.closed ?? 0),
    open: (linear?.open ?? 0) + (jira?.open ?? 0),
    bugsReported:
      (linear?.bugsReported ?? 0) + (jira?.bugsReported ?? 0),
  };
}
